name: Lint project with terraform lint

on:
  push:
  pull_request:
    
jobs: 
  lint:
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
