name: Lint project with terraform lint

on:
  pull_request:
  push:
    branches:
      - "main"
    
jobs: 
  lint:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check
